/* tslint:disable */
/* eslint-disable */
/**
 * Sunday School API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { GoogleCalendarEventsResponse } from '../models';
import { StoreCalednerDto } from '../models';
/**
 * GoogleEventsApi - axios parameter creator
 * @export
 */
export const GoogleEventsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllEvents: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/google-events`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {StoreCalednerDto} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        storeCalendar: async (body: StoreCalednerDto, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling storeCalendar.');
            }
            const localVarPath = `/google-events`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers!['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * GoogleEventsApi - functional programming interface
 * @export
 */
export const GoogleEventsApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllEvents(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<GoogleCalendarEventsResponse>>> {
            const localVarAxiosArgs = await GoogleEventsApiAxiosParamCreator(configuration).getAllEvents(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {StoreCalednerDto} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async storeCalendar(body: StoreCalednerDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await GoogleEventsApiAxiosParamCreator(configuration).storeCalendar(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * GoogleEventsApi - factory interface
 * @export
 */
export const GoogleEventsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllEvents(options?: AxiosRequestConfig): Promise<AxiosResponse<GoogleCalendarEventsResponse>> {
            return GoogleEventsApiFp(configuration).getAllEvents(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {StoreCalednerDto} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async storeCalendar(body: StoreCalednerDto, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return GoogleEventsApiFp(configuration).storeCalendar(body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * GoogleEventsApi - object-oriented interface
 * @export
 * @class GoogleEventsApi
 * @extends {BaseAPI}
 */
export class GoogleEventsApi extends BaseAPI {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GoogleEventsApi
     */
    public async getAllEvents(options?: AxiosRequestConfig) : Promise<AxiosResponse<GoogleCalendarEventsResponse>> {
        return GoogleEventsApiFp(this.configuration).getAllEvents(options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {StoreCalednerDto} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GoogleEventsApi
     */
    public async storeCalendar(body: StoreCalednerDto, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return GoogleEventsApiFp(this.configuration).storeCalendar(body, options).then((request) => request(this.axios, this.basePath));
    }
}
