/* tslint:disable */
/* eslint-disable */
/**
 * Tiker App API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
export * from './apis/auth-api';
export * from './apis/banners-api';
export * from './apis/banners-mails-api';
export * from './apis/categories-types-api';
export * from './apis/coupons-api';
export * from './apis/stickers-api';
export * from './apis/stickers-categories-api';
export * from './apis/stickers-packs-api';
export * from './apis/stickers-tags-api';
export * from './apis/users-api';

