/* tslint:disable */
/* eslint-disable */
/**
 * Sunday School API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface CreateNotificationDto
 */
export interface CreateNotificationDto {

    /**
     * @type {string}
     * @memberof CreateNotificationDto
     */
    title?: string;

    /**
     * @type {string}
     * @memberof CreateNotificationDto
     */
    message?: string;

    /**
     * @type {Array<string>}
     * @memberof CreateNotificationDto
     */
    notificationCategories?: Array<string>;

    /**
     * @type {Array<string>}
     * @memberof CreateNotificationDto
     */
    rolesArray?: Array<string>;

    /**
     * @type {Array<string>}
     * @memberof CreateNotificationDto
     */
    usersIds?: Array<string>;

    /**
     * @type {Array<string>}
     * @memberof CreateNotificationDto
     */
    filterStates?: Array<string>;
}
