/* tslint:disable */
/* eslint-disable */
/**
 * Tiker App API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface CreateUserDto
 */
export interface CreateUserDto {

    /**
     * @type {string}
     * @memberof CreateUserDto
     */
    name: string;

    /**
     * @type {string}
     * @memberof CreateUserDto
     */
    email: string;

    /**
     * @type {string}
     * @memberof CreateUserDto
     */
    password: string;

    /**
     * @type {string}
     * @memberof CreateUserDto
     */
    role: CreateUserDtoRoleEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum CreateUserDtoRoleEnum {
    SuperAdmin = 'superAdmin',
    Admin = 'Admin',
    User = 'user'
}

