/* tslint:disable */
/* eslint-disable */
/**
 * Sunday School API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface CreateAuthDto
 */
export interface CreateAuthDto {

    /**
     * @type {string}
     * @memberof CreateAuthDto
     */
    email?: string;

    /**
     * @type {string}
     * @memberof CreateAuthDto
     */
    password?: string;

    /**
     * @type {string}
     * @memberof CreateAuthDto
     */
    accessToken?: string;

    /**
     * @type {string}
     * @memberof CreateAuthDto
     */
    user?: string;

    /**
     * @type {string}
     * @memberof CreateAuthDto
     */
    appleId?: string;

    /**
     * @type {string}
     * @memberof CreateAuthDto
     */
    firstname?: string;

    /**
     * @type {string}
     * @memberof CreateAuthDto
     */
    lastname?: string;

    /**
     * @type {Date}
     * @memberof CreateAuthDto
     */
    dateOfBirth?: Date;

    /**
     * @type {number}
     * @memberof CreateAuthDto
     */
    userAge?: number;
}
