/* tslint:disable */
/* eslint-disable */
/**
 * Sunday School API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ObjectId } from './object-id';
import { RepeatedAssignment } from './repeated-assignment';
import { SingleClassTimeSlot } from './single-class-time-slot';
 /**
 * 
 *
 * @export
 * @interface CreateClassDto
 */
export interface CreateClassDto {

    /**
     * @type {string}
     * @memberof CreateClassDto
     */
    className: string;

    /**
     * @type {ObjectId}
     * @memberof CreateClassDto
     */
    classService: ObjectId;

    /**
     * @type {Array<ObjectId>}
     * @memberof CreateClassDto
     */
    classServants: Array<ObjectId>;

    /**
     * @type {Array<ObjectId>}
     * @memberof CreateClassDto
     */
    classUsers: Array<ObjectId>;

    /**
     * @type {ObjectId}
     * @memberof CreateClassDto
     */
    trustee: ObjectId;

    /**
     * @type {string}
     * @memberof CreateClassDto
     */
    classGrade: string;

    /**
     * @type {string}
     * @memberof CreateClassDto
     */
    notes?: string;

    /**
     * @type {Array<number>}
     * @memberof CreateClassDto
     */
    byweekday: Array<number>;

    /**
     * @type {Array<SingleClassTimeSlot>}
     * @memberof CreateClassDto
     */
    timeSlots: Array<SingleClassTimeSlot>;

    /**
     * @type {Array<RepeatedAssignment>}
     * @memberof CreateClassDto
     */
    repeatedAssignments: Array<RepeatedAssignment>;

    /**
     * @type {string}
     * @memberof CreateClassDto
     */
    rrule?: string;
}
