/* tslint:disable */
/* eslint-disable */
/**
 * Tiker App API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface CreateBannerDto
 */
export interface CreateBannerDto {

    /**
     * @type {string}
     * @memberof CreateBannerDto
     */
    image: string;

    /**
     * @type {string}
     * @memberof CreateBannerDto
     */
    link: string;

    /**
     * @type {string}
     * @memberof CreateBannerDto
     */
    type: string;

    /**
     * @type {string}
     * @memberof CreateBannerDto
     */
    userType: string;

    /**
     * @type {string}
     * @memberof CreateBannerDto
     */
    categoryType: string;
}
