/* tslint:disable */
/* eslint-disable */
/**
 * Sunday School API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ObjectId } from './object-id';
 /**
 * 
 *
 * @export
 * @interface CreateServiceDto
 */
export interface CreateServiceDto {

    /**
     * The name of the Service
     *
     * @type {string}
     * @memberof CreateServiceDto
     * @example Sunday school
     */
    serviceName: string;

    /**
     * @type {string}
     * @memberof CreateServiceDto
     */
    notes: string;

    /**
     * @type {ObjectId}
     * @memberof CreateServiceDto
     */
    trustee: ObjectId;
}
