/* tslint:disable */
/* eslint-disable */
/**
 * Sunday School API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { SingelCustomFieldDTO } from './singel-custom-field-dto';
 /**
 * 
 *
 * @export
 * @interface Event
 */
export interface Event {

    /**
     * @type {string}
     * @memberof Event
     */
    id: string;

    /**
     * @type {string}
     * @memberof Event
     */
    eventName: string;

    /**
     * @type {string}
     * @memberof Event
     */
    eventType: string;

    /**
     * @type {string}
     * @memberof Event
     */
    photo: string;

    /**
     * @type {string}
     * @memberof Event
     */
    rrule: string;

    /**
     * @type {Array<string>}
     * @memberof Event
     */
    classes: Array<string>;

    /**
     * @type {string}
     * @memberof Event
     */
    cost: string;

    /**
     * @type {Date}
     * @memberof Event
     */
    startDate: Date;

    /**
     * @type {Date}
     * @memberof Event
     */
    endDate: Date;

    /**
     * @type {string}
     * @memberof Event
     */
    dropOffLocation: string;

    /**
     * @type {string}
     * @memberof Event
     */
    pickupLocation: string;

    /**
     * @type {string}
     * @memberof Event
     */
    eventLocation: string;

    /**
     * @type {boolean}
     * @memberof Event
     */
    atChurch: boolean;

    /**
     * @type {boolean}
     * @memberof Event
     */
    isFree: boolean;

    /**
     * @type {string}
     * @memberof Event
     */
    eventInfo: string;

    /**
     * @type {string}
     * @memberof Event
     */
    notes: string;

    /**
     * @type {string}
     * @memberof Event
     */
    consentParagraph: string;

    /**
     * @type {number}
     * @memberof Event
     */
    freq: number;

    /**
     * @type {number}
     * @memberof Event
     */
    interval: number;

    /**
     * @type {Array<number>}
     * @memberof Event
     */
    byweekday: Array<number>;

    /**
     * @type {Array<number>}
     * @memberof Event
     */
    bysetpos: Array<number>;

    /**
     * @type {number}
     * @memberof Event
     */
    count: number;

    /**
     * @type {Array<number>}
     * @memberof Event
     */
    bymonth: Array<number>;

    /**
     * @type {Array<number>}
     * @memberof Event
     */
    bymonthday: Array<number>;

    /**
     * @type {Array<number>}
     * @memberof Event
     */
    byyearday: Array<number>;

    /**
     * @type {Array<number>}
     * @memberof Event
     */
    byweekno: Array<number>;

    /**
     * @type {Array<number>}
     * @memberof Event
     */
    bynweekday: Array<number>;

    /**
     * @type {Date}
     * @memberof Event
     */
    until: Date;

    /**
     * @type {Date}
     * @memberof Event
     */
    dtstart: Date;

    /**
     * @type {Array<SingelCustomFieldDTO>}
     * @memberof Event
     */
    customFields?: Array<SingelCustomFieldDTO>;

    /**
     * @type {Date}
     * @memberof Event
     */
    registrationDeadLine?: Date;

    /**
     * @type {number}
     * @memberof Event
     */
    capacity?: number;

    /**
     * @type {boolean}
     * @memberof Event
     */
    collectPayments?: boolean;

    /**
     * @type {boolean}
     * @memberof Event
     */
    registrationIsEnabled?: boolean;
}
