/* tslint:disable */
/* eslint-disable */
/**
 * Sunday School API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { User } from './user';
 /**
 * 
 *
 * @export
 * @interface GetAllUsersType
 */
export interface GetAllUsersType {

    /**
     * @type {boolean}
     * @memberof GetAllUsersType
     */
    hasNextPage: boolean;

    /**
     * @type {number}
     * @memberof GetAllUsersType
     */
    nextPage: number | null;

    /**
     * @type {Array<User>}
     * @memberof GetAllUsersType
     */
    users: Array<User>;
}
