/* tslint:disable */
/* eslint-disable */
/**
 * Sunday School API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface GoogleEventTimeDto
 */
export interface GoogleEventTimeDto {

    /**
     * @type {Date}
     * @memberof GoogleEventTimeDto
     */
    dateTime: Date;

    /**
     * @type {string}
     * @memberof GoogleEventTimeDto
     */
    timeZone: string;

    /**
     * @type {string}
     * @memberof GoogleEventTimeDto
     */
    dateFormated: string;
}
