/* tslint:disable */
/* eslint-disable */
/**
 * Sunday School API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { GoogleEventTimeDto } from './google-event-time-dto';
 /**
 * 
 *
 * @export
 * @interface GoogleEvent
 */
export interface GoogleEvent {

    /**
     * @type {string}
     * @memberof GoogleEvent
     */
    id: string;

    /**
     * @type {string}
     * @memberof GoogleEvent
     */
    summary: string;

    /**
     * @type {GoogleEventTimeDto}
     * @memberof GoogleEvent
     */
    start: GoogleEventTimeDto;

    /**
     * @type {GoogleEventTimeDto}
     * @memberof GoogleEvent
     */
    end: GoogleEventTimeDto;
}
