/* tslint:disable */
/* eslint-disable */
/**
 * Sunday School API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ObjectId } from './object-id';
 /**
 * 
 *
 * @export
 * @interface Lesson
 */
export interface Lesson {

    /**
     * @type {string}
     * @memberof Lesson
     */
    id: string;

    /**
     * @type {string}
     * @memberof Lesson
     */
    churchSeason: string;

    /**
     * @type {Date}
     * @memberof Lesson
     */
    date: Date;

    /**
     * @type {string}
     * @memberof Lesson
     */
    notes: string;

    /**
     * @type {string}
     * @memberof Lesson
     */
    lessonNumber: string;

    /**
     * @type {ObjectId}
     * @memberof Lesson
     */
    singleClass: ObjectId;

    /**
     * @type {string}
     * @memberof Lesson
     */
    lessonTitle: string;

    /**
     * @type {ObjectId}
     * @memberof Lesson
     */
    responsibleServantId: ObjectId;

    /**
     * @type {Date}
     * @memberof Lesson
     */
    createdAt: Date;

    /**
     * @type {Date}
     * @memberof Lesson
     */
    updatedAt: Date;
}
