/* tslint:disable */
/* eslint-disable */
/**
 * Sunday School API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { User } from './user';
 /**
 * 
 *
 * @export
 * @interface ModifiedFamily
 */
export interface ModifiedFamily {

    /**
     * @type {any}
     * @memberof ModifiedFamily
     */
    id: any;

    /**
     * @type {string}
     * @memberof ModifiedFamily
     */
    familyLastName: string;

    /**
     * @type {string}
     * @memberof ModifiedFamily
     */
    familyAddress: string;

    /**
     * @type {Array<User>}
     * @memberof ModifiedFamily
     */
    individuals: Array<User>;
}
