/* tslint:disable */
/* eslint-disable */
/**
 * Sunday School API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Attendance } from './attendance';
import { ModifiedAssignment } from './modified-assignment';
import { NewService } from './new-service';
import { PopulatedOutReach } from './populated-out-reach';
import { SingleClassTimeSlot } from './single-class-time-slot';
 /**
 * 
 *
 * @export
 * @interface ModifiedClass
 */
export interface ModifiedClass {

    /**
     * @type {string}
     * @memberof ModifiedClass
     */
    id: string;

    /**
     * @type {string}
     * @memberof ModifiedClass
     */
    className: string;

    /**
     * @type {NewService}
     * @memberof ModifiedClass
     */
    classService: NewService;

    /**
     * @type {string}
     * @memberof ModifiedClass
     */
    notes: string;

    /**
     * @type {string}
     * @memberof ModifiedClass
     */
    classGrade: string;

    /**
     * @type {string}
     * @memberof ModifiedClass
     */
    rrule: string;

    /**
     * @type {Array<number>}
     * @memberof ModifiedClass
     */
    byweekday: Array<number>;

    /**
     * @type {Array<SingleClassTimeSlot>}
     * @memberof ModifiedClass
     */
    timeSlots: Array<SingleClassTimeSlot>;

    /**
     * @type {Array<Attendance>}
     * @memberof ModifiedClass
     */
    userAttendance: Array<Attendance>;

    /**
     * @type {Array<ModifiedAssignment>}
     * @memberof ModifiedClass
     */
    userAssignments: Array<ModifiedAssignment>;

    /**
     * @type {Array<PopulatedOutReach>}
     * @memberof ModifiedClass
     */
    userOutReaches: Array<PopulatedOutReach>;
}
