/* tslint:disable */
/* eslint-disable */
/**
 * Sunday School API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ObjectId } from './object-id';
 /**
 * 
 *
 * @export
 * @interface OutReach
 */
export interface OutReach {

    /**
     * @type {string}
     * @memberof OutReach
     */
    id: string;

    /**
     * @type {ObjectId}
     * @memberof OutReach
     */
    user: ObjectId;

    /**
     * @type {ObjectId}
     * @memberof OutReach
     */
    classId: ObjectId;

    /**
     * @type {Array<ObjectId>}
     * @memberof OutReach
     */
    servants: Array<ObjectId>;

    /**
     * @type {string}
     * @memberof OutReach
     */
    notes: string;

    /**
     * @type {Date}
     * @memberof OutReach
     */
    dateTime: Date;

    /**
     * @type {Date}
     * @memberof OutReach
     */
    doneAt: Date;

    /**
     * @type {string}
     * @memberof OutReach
     */
    status: string;

    /**
     * @type {Date}
     * @memberof OutReach
     */
    createdAt: Date;

    /**
     * @type {Date}
     * @memberof OutReach
     */
    updatedAt: Date;
}
