/* tslint:disable */
/* eslint-disable */
/**
 * Sunday School API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface PendingUserDTO
 */
export interface PendingUserDTO {

    /**
     * @type {string}
     * @memberof PendingUserDTO
     */
    email?: string;

    /**
     * @type {string}
     * @memberof PendingUserDTO
     */
    firstName?: string;

    /**
     * @type {string}
     * @memberof PendingUserDTO
     */
    lastName?: string;

    /**
     * @type {string}
     * @memberof PendingUserDTO
     */
    familyMember?: string;

    /**
     * @type {string}
     * @memberof PendingUserDTO
     */
    phoneNumber?: string;
}
