/* tslint:disable */
/* eslint-disable */
/**
 * Sunday School API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ObjectId } from './object-id';
import { User } from './user';
 /**
 * 
 *
 * @export
 * @interface PopulatedAttendance
 */
export interface PopulatedAttendance {

    /**
     * @type {string}
     * @memberof PopulatedAttendance
     */
    id: string;

    /**
     * @type {ObjectId}
     * @memberof PopulatedAttendance
     */
    singleClass: ObjectId;

    /**
     * @type {User}
     * @memberof PopulatedAttendance
     */
    user: User;

    /**
     * @type {Date}
     * @memberof PopulatedAttendance
     */
    dateTime: Date;

    /**
     * @type {boolean}
     * @memberof PopulatedAttendance
     */
    present: boolean;

    /**
     * @type {boolean}
     * @memberof PopulatedAttendance
     */
    tardiness: boolean;

    /**
     * @type {boolean}
     * @memberof PopulatedAttendance
     */
    excusedAbsence: boolean;

    /**
     * @type {boolean}
     * @memberof PopulatedAttendance
     */
    badBehavior: boolean;

    /**
     * @type {string}
     * @memberof PopulatedAttendance
     */
    notes?: string;
}
