/* tslint:disable */
/* eslint-disable */
/**
 * Sunday School API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ObjectId } from './object-id';
import { PopulatedClass } from './populated-class';
 /**
 * 
 *
 * @export
 * @interface PopulatedServiceWithClasses
 */
export interface PopulatedServiceWithClasses {

    /**
     * @type {string}
     * @memberof PopulatedServiceWithClasses
     */
    id: string;

    /**
     * @type {string}
     * @memberof PopulatedServiceWithClasses
     */
    serviceName: string;

    /**
     * @type {string}
     * @memberof PopulatedServiceWithClasses
     */
    notes: string;

    /**
     * @type {ObjectId}
     * @memberof PopulatedServiceWithClasses
     */
    trustee: ObjectId;

    /**
     * @type {Array<PopulatedClass>}
     * @memberof PopulatedServiceWithClasses
     */
    classes: Array<PopulatedClass>;
}
