/* tslint:disable */
/* eslint-disable */
/**
 * Sunday School API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface RegisterWithEmailDTO
 */
export interface RegisterWithEmailDTO {

    /**
     * @type {string}
     * @memberof RegisterWithEmailDTO
     */
    email: string;

    /**
     * @type {string}
     * @memberof RegisterWithEmailDTO
     */
    password: string;

    /**
     * @type {string}
     * @memberof RegisterWithEmailDTO
     */
    firstname?: string;

    /**
     * @type {string}
     * @memberof RegisterWithEmailDTO
     */
    lastname?: string;

    /**
     * @type {Date}
     * @memberof RegisterWithEmailDTO
     */
    dateOfBirth?: Date;
}
