/* tslint:disable */
/* eslint-disable */
/**
 * Sunday School API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface SinglePayment
 */
export interface SinglePayment {

    /**
     * @type {string}
     * @memberof SinglePayment
     */
    id: string;

    /**
     * @type {string}
     * @memberof SinglePayment
     */
    status: string;

    /**
     * @type {number}
     * @memberof SinglePayment
     */
    amount: number;

    /**
     * @type {number}
     * @memberof SinglePayment
     */
    createdAt: number;

    /**
     * @type {string}
     * @memberof SinglePayment
     */
    currency: string;

    /**
     * @type {string}
     * @memberof SinglePayment
     */
    receiptEmail: string;

    /**
     * @type {string}
     * @memberof SinglePayment
     */
    invoice: string;

    /**
     * @type {string}
     * @memberof SinglePayment
     */
    reason: string;
}
