/* tslint:disable */
/* eslint-disable */
/**
 * Sunday School API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { GoogleEvent } from './google-event';
 /**
 * 
 *
 * @export
 * @interface StoreCalednerDto
 */
export interface StoreCalednerDto {

    /**
     * @type {Array<GoogleEvent>}
     * @memberof StoreCalednerDto
     */
    calendar: Array<GoogleEvent>;
}
