/* tslint:disable */
/* eslint-disable */
/**
 * Tiker App API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { User } from './user';
 /**
 * 
 *
 * @export
 * @interface TUserSessionData
 */
export interface TUserSessionData {

    /**
     * User Data
     *
     * @type {User}
     * @memberof TUserSessionData
     */
    userData: User;

    /**
     * @type {string}
     * @memberof TUserSessionData
     */
    authToken: string;
}
