/* tslint:disable */
/* eslint-disable */
/**
 * Tiker App API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface UpdateCouponDto
 */
export interface UpdateCouponDto {

    /**
     * @type {string}
     * @memberof UpdateCouponDto
     */
    code?: string;

    /**
     * @type {Date}
     * @memberof UpdateCouponDto
     */
    startDate?: Date;

    /**
     * @type {Date}
     * @memberof UpdateCouponDto
     */
    endDate?: Date;

    /**
     * @type {boolean}
     * @memberof UpdateCouponDto
     */
    isActive?: boolean;

    /**
     * @type {number}
     * @memberof UpdateCouponDto
     */
    maxUseCount?: number;
}
