/* tslint:disable */
/* eslint-disable */
/**
 * Sunday School API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { AssignmentType } from './assignment-type';
import { ObjectId } from './object-id';
 /**
 * 
 *
 * @export
 * @interface UpdateAttendanceDto
 */
export interface UpdateAttendanceDto {

    /**
     * @type {ObjectId}
     * @memberof UpdateAttendanceDto
     */
    service?: ObjectId;

    /**
     * @type {string}
     * @memberof UpdateAttendanceDto
     */
    grade?: string;

    /**
     * @type {ObjectId}
     * @memberof UpdateAttendanceDto
     */
    singleClass?: ObjectId;

    /**
     * @type {ObjectId}
     * @memberof UpdateAttendanceDto
     */
    user?: ObjectId;

    /**
     * @type {Array<AssignmentType>}
     * @memberof UpdateAttendanceDto
     */
    assignment?: Array<AssignmentType>;

    /**
     * @type {Date}
     * @memberof UpdateAttendanceDto
     */
    dateTime?: Date;

    /**
     * @type {boolean}
     * @memberof UpdateAttendanceDto
     */
    present?: boolean;

    /**
     * @type {string}
     * @memberof UpdateAttendanceDto
     */
    notes?: string;

    /**
     * @type {boolean}
     * @memberof UpdateAttendanceDto
     */
    tardiness?: boolean;

    /**
     * @type {boolean}
     * @memberof UpdateAttendanceDto
     */
    excusedAbsence?: boolean;

    /**
     * @type {boolean}
     * @memberof UpdateAttendanceDto
     */
    badBehavior?: boolean;
}
