/* tslint:disable */
/* eslint-disable */
/**
 * Sunday School API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ObjectId } from './object-id';
import { RepeatedAssignment } from './repeated-assignment';
import { SingleClassTimeSlot } from './single-class-time-slot';
 /**
 * 
 *
 * @export
 * @interface UpdateClassDto
 */
export interface UpdateClassDto {

    /**
     * @type {string}
     * @memberof UpdateClassDto
     */
    className?: string;

    /**
     * @type {ObjectId}
     * @memberof UpdateClassDto
     */
    classService?: ObjectId;

    /**
     * @type {Array<ObjectId>}
     * @memberof UpdateClassDto
     */
    classServants?: Array<ObjectId>;

    /**
     * @type {Array<ObjectId>}
     * @memberof UpdateClassDto
     */
    classUsers?: Array<ObjectId>;

    /**
     * @type {ObjectId}
     * @memberof UpdateClassDto
     */
    trustee?: ObjectId;

    /**
     * @type {string}
     * @memberof UpdateClassDto
     */
    classGrade?: string;

    /**
     * @type {string}
     * @memberof UpdateClassDto
     */
    notes?: string;

    /**
     * @type {Array<number>}
     * @memberof UpdateClassDto
     */
    byweekday?: Array<number>;

    /**
     * @type {Array<SingleClassTimeSlot>}
     * @memberof UpdateClassDto
     */
    timeSlots?: Array<SingleClassTimeSlot>;

    /**
     * @type {Array<RepeatedAssignment>}
     * @memberof UpdateClassDto
     */
    repeatedAssignments?: Array<RepeatedAssignment>;

    /**
     * @type {string}
     * @memberof UpdateClassDto
     */
    rrule?: string;
}
