/* tslint:disable */
/* eslint-disable */
/**
 * Tiker App API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface UpdateCategoriesTypeDto
 */
export interface UpdateCategoriesTypeDto {

    /**
     * @type {string}
     * @memberof UpdateCategoriesTypeDto
     */
    name?: string;

    /**
     * @type {string}
     * @memberof UpdateCategoriesTypeDto
     */
    hexColor?: string;
}
