/* tslint:disable */
/* eslint-disable */
/**
 * Tiker App API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface UpdateUserDto
 */
export interface UpdateUserDto {

    /**
     * @type {string}
     * @memberof UpdateUserDto
     */
    name?: string;

    /**
     * @type {string}
     * @memberof UpdateUserDto
     */
    email?: string;

    /**
     * @type {string}
     * @memberof UpdateUserDto
     */
    password?: string;

    /**
     * @type {string}
     * @memberof UpdateUserDto
     */
    role?: UpdateUserDtoRoleEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum UpdateUserDtoRoleEnum {
    SuperAdmin = 'superAdmin',
    Admin = 'Admin',
    User = 'user'
}

