/* tslint:disable */
/* eslint-disable */
/**
 * Sunday School API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ObjectId } from './object-id';
 /**
 * 
 *
 * @export
 * @interface UpdateOutreachDto
 */
export interface UpdateOutreachDto {

    /**
     * @type {ObjectId}
     * @memberof UpdateOutreachDto
     */
    user?: ObjectId;

    /**
     * @type {ObjectId}
     * @memberof UpdateOutreachDto
     */
    classId?: ObjectId;

    /**
     * @type {Array<ObjectId>}
     * @memberof UpdateOutreachDto
     */
    servants?: Array<ObjectId>;

    /**
     * @type {string}
     * @memberof UpdateOutreachDto
     */
    notes?: string;

    /**
     * @type {Date}
     * @memberof UpdateOutreachDto
     */
    dateTime?: Date;

    /**
     * @type {string}
     * @memberof UpdateOutreachDto
     */
    status?: string;
}
