/* tslint:disable */
/* eslint-disable */
/**
 * Sunday School API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Attendance } from './attendance';
import { ObjectId } from './object-id';
import { OutReach } from './out-reach';
 /**
 * 
 *
 * @export
 * @interface User
 */
export interface User {

    /**
     * @type {ObjectId}
     * @memberof User
     */
    id: ObjectId;

    /**
     * @type {string}
     * @memberof User
     */
    email: string;

    /**
     * @type {boolean}
     * @memberof User
     */
    isEmailVerified: boolean;

    /**
     * @type {string}
     * @memberof User
     */
    contactEmail: string;

    /**
     * @type {string}
     * @memberof User
     */
    password: string;

    /**
     * @type {string}
     * @memberof User
     */
    firstname: string;

    /**
     * @type {string}
     * @memberof User
     */
    lastname: string;

    /**
     * @type {string}
     * @memberof User
     */
    role: UserRoleEnum;

    /**
     * @type {Date}
     * @memberof User
     */
    dateOfBirth: Date;

    /**
     * @type {string}
     * @memberof User
     */
    grade: string;

    /**
     * @type {boolean}
     * @memberof User
     */
    locationEnabled: boolean;

    /**
     * @type {string}
     * @memberof User
     */
    notificationsToken: string;

    /**
     * @type {Attendance}
     * @memberof User
     */
    lastAttendance: Attendance;

    /**
     * @type {string}
     * @memberof User
     */
    tempLastAttendance: string;

    /**
     * @type {OutReach}
     * @memberof User
     */
    lastOutReach: OutReach;

    /**
     * @type {Date}
     * @memberof User
     */
    lastShow: Date;

    /**
     * @type {Date}
     * @memberof User
     */
    lastSeen: Date;

    /**
     * @type {Date}
     * @memberof User
     */
    lastLogin: Date;

    /**
     * @type {number}
     * @memberof User
     */
    userAge: number;

    /**
     * @type {string}
     * @memberof User
     */
    address: string;

    /**
     * @type {string}
     * @memberof User
     */
    floorNumber: string;

    /**
     * @type {string}
     * @memberof User
     */
    apartmentNumber: string;

    /**
     * @type {string}
     * @memberof User
     */
    houseNumber: string;

    /**
     * @type {string}
     * @memberof User
     */
    maritalStatus: string;

    /**
     * @type {string}
     * @memberof User
     */
    phoneNumber: string;

    /**
     * @type {string}
     * @memberof User
     */
    homeNumber: string;

    /**
     * @type {string}
     * @memberof User
     */
    avatar: string;

    /**
     * @type {string}
     * @memberof User
     */
    churchName: string;

    /**
     * @type {Array<string>}
     * @memberof User
     */
    liturgy: Array<string>;

    /**
     * @type {Array<string>}
     * @memberof User
     */
    availability: Array<string>;

    /**
     * @type {string}
     * @memberof User
     */
    fatherOfConfession: string;

    /**
     * @type {Array<string>}
     * @memberof User
     */
    notificationsCategories: Array<string>;

    /**
     * @type {string}
     * @memberof User
     */
    registrationMethod: string;

    /**
     * @type {string}
     * @memberof User
     */
    appleId: string;

    /**
     * @type {ObjectId}
     * @memberof User
     */
    family: ObjectId;

    /**
     * @type {ObjectId}
     * @memberof User
     */
    responsibleServant: ObjectId;

    /**
     * @type {number}
     * @memberof User
     */
    temporaryServantId: number;

    /**
     * @type {number}
     * @memberof User
     */
    temporaryStudentId: number;

    /**
     * @type {number}
     * @memberof User
     */
    temporaryFamilyId: number;

    /**
     * @type {string}
     * @memberof User
     */
    gender: string;

    /**
     * @type {string}
     * @memberof User
     */
    notes: string;

    /**
     * @type {string}
     * @memberof User
     */
    activeStatus?: string;

    /**
     * @type {string}
     * @memberof User
     */
    activeStatusNotes?: string;

    /**
     * @type {string}
     * @memberof User
     */
    familyMember?: string;

    /**
     * @type {Date}
     * @memberof User
     */
    createdAt: Date;

    /**
     * @type {Date}
     * @memberof User
     */
    updatedAt: Date;
}

/**
 * @export
 * @enum {string}
 */
export enum UserRoleEnum {
    SuperAdmin = 'superAdmin',
    Admin = 'admin',
    Maintenence = 'Maintenence',
    Priest = 'Priest',
    Servant = 'Servant',
    User = 'user'
}

